import { requireUserProfile } from '@/lib/auth/guards'
import { selectableParticipantTypes, participantTypeLabels } from '@/lib/auth/access'
import { updateProfile, uploadAvatar, removeAvatar } from './actions'
import { Avatar } from '@/components/avatar'
import { SubmitButton } from '@/components/submit-button'

type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> }
export default async function ProfilePage({ searchParams }: Props) {
  const { profile } = await requireUserProfile(); const params = await searchParams
  const error = typeof params.error === 'string' ? params.error : null; const message = typeof params.message === 'string' ? params.message : null
  const lockedType = profile.verification_status === 'verified'
  return <div className="page-stack narrow-content"><div><p className="eyebrow">Account profile</p><h1>Profile and participant details</h1><p className="muted">Complete this information before requesting WTC Accra verification.</p></div>{error && <div className="alert alert-error">{error}</div>}{message && <div className="alert alert-success">{message}</div>}<section className="card"><h2>Profile photo</h2><p className="muted">Shown on your listings, bids, the member directory and deal rooms.</p><div className="avatar-upload"><Avatar src={profile.avatar_url} name={profile.full_name} size={96} /><form action={uploadAvatar} className="form-stack"><label>New photo<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp" required /></label><p className="field-help">JPG, PNG or WebP, up to 5MB. Square images look best.</p><div className="button-row"><SubmitButton pendingLabel="Uploading…">Upload photo</SubmitButton>{profile.avatar_url && <button className="button button-outline" formAction={removeAvatar} type="submit">Remove</button>}</div></form></div></section><form action={updateProfile} className="card form-stack"><label>Full name<input name="fullName" defaultValue={profile.full_name} required /></label><div className="form-grid"><label>Phone<input name="phone" defaultValue={profile.phone ?? ''} /></label><label>Job title<input name="jobTitle" defaultValue={profile.job_title ?? ''} /></label></div><div className="form-grid"><label>Country<input name="country" defaultValue={profile.country ?? ''} /></label><label>City<input name="city" defaultValue={profile.city ?? ''} /></label></div><label>Participant type<select name="participantType" defaultValue={profile.requested_participant_type ?? ''} disabled={lockedType} required><option value="" disabled>Select account type</option>{selectableParticipantTypes.map(type => <option key={type} value={type}>{participantTypeLabels[type]}</option>)}</select></label>{lockedType && <p className="field-help">Your approved participant type is locked. WTC Accra must review any membership-type change.</p>}<button className="button button-primary" type="submit">Save profile</button></form></div>
}
