import { requireUserProfile } from '@/lib/auth/guards'
import { updateProfile } from './actions'

type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> }
export default async function ProfilePage({ searchParams }: Props) {
  const { profile } = await requireUserProfile(); const params = await searchParams
  const error = typeof params.error === 'string' ? params.error : null; const message = typeof params.message === 'string' ? params.message : null
  const lockedType = profile.verification_status === 'verified'
  return <div className="page-stack narrow-content"><div><p className="eyebrow">Account profile</p><h1>Profile and participant details</h1><p className="muted">Complete this information before requesting WTC Accra verification.</p></div>{error && <div className="alert alert-error">{error}</div>}{message && <div className="alert alert-success">{message}</div>}<form action={updateProfile} className="card form-stack"><label>Full name<input name="fullName" defaultValue={profile.full_name} required /></label><div className="form-grid"><label>Phone<input name="phone" defaultValue={profile.phone ?? ''} /></label><label>Job title<input name="jobTitle" defaultValue={profile.job_title ?? ''} /></label></div><div className="form-grid"><label>Country<input name="country" defaultValue={profile.country ?? ''} /></label><label>City<input name="city" defaultValue={profile.city ?? ''} /></label></div><label>Participant type<select name="participantType" defaultValue={profile.requested_participant_type ?? ''} disabled={lockedType} required><option value="" disabled>Select account type</option><option value="investor">Investor</option><option value="buyer">Buyer</option><option value="business">Business</option><option value="project_sponsor">Project sponsor</option><option value="wtc_association_member">WTC Association member</option><option value="wtc_accra_member">WTC Accra member</option></select></label>{lockedType && <p className="field-help">Your approved participant type is locked. WTC Accra must review any membership-type change.</p>}<button className="button button-primary" type="submit">Save profile</button></form></div>
}
