'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Enrollment = { factorId: string; qrCode: string; secret: string }
export function MfaClient({ adminRequired }: { adminRequired: boolean }) {
  const router = useRouter(); const supabase = createClient(); const [loading,setLoading]=useState(true); const [currentLevel,setCurrentLevel]=useState<string|null>(null); const [verifiedFactorId,setVerifiedFactorId]=useState<string|null>(null); const [enrollment,setEnrollment]=useState<Enrollment|null>(null); const [code,setCode]=useState(''); const [error,setError]=useState<string|null>(null)
  async function refreshSecurityState(){ setLoading(true); const [{data:aalData,error:aalError},{data:factorData,error:factorError}] = await Promise.all([supabase.auth.mfa.getAuthenticatorAssuranceLevel(),supabase.auth.mfa.listFactors()]); if(aalError||factorError){setError(aalError?.message||factorError?.message||'Unable to load MFA settings.');setLoading(false);return} setCurrentLevel(aalData.currentLevel); const verified=factorData.totp.find((factor)=>factor.status==='verified'); setVerifiedFactorId(verified?.id??null); setLoading(false) }
  useEffect(()=>{void refreshSecurityState()},[])
  async function enroll(){setError(null);setLoading(true);const {data,error:enrollError}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'WTC Accra Hub'});if(enrollError){const code=(enrollError as {code?:string}).code??'';setError(/not_enabled|disabled/i.test(code+enrollError.message)?'Authenticator (TOTP) enrolment is switched off for this project. Enable it in Supabase under Authentication → Multi-Factor, then try again.':enrollError.message);setLoading(false);return}setEnrollment({factorId:data.id,qrCode:data.totp.qr_code,secret:data.totp.secret});setLoading(false)}
  async function verify(){const factorId=enrollment?.factorId??verifiedFactorId;if(!factorId||code.trim().length<6){setError('Enter the 6-digit code from your authenticator app.');return}setError(null);setLoading(true);const {error:verifyError}=await supabase.auth.mfa.challengeAndVerify({factorId,code:code.trim()});if(verifyError){setError(verifyError.message);setLoading(false);return}setEnrollment(null);setCode('');await refreshSecurityState();router.refresh();if(adminRequired)router.push('/admin')}
  if(loading)return <section className="card"><p>Loading security settings…</p></section>
  if(currentLevel==='aal2')return <section className="card status-card"><span className="status-dot status-verified">MFA active</span><h2>Two-factor authentication confirmed</h2><p>Your current session meets the AAL2 requirement for WTC Accra administrative access.</p>{adminRequired&&<button className="button button-primary" onClick={()=>router.push('/admin')}>Continue to administration</button>}</section>
  if(enrollment)return <section className="card form-stack"><h2>Scan the authenticator QR code</h2><p className="muted">Use Google Authenticator, Microsoft Authenticator, 1Password or another TOTP-compatible app.</p><img className="mfa-qr" src={enrollment.qrCode} alt="Authenticator QR code" /><p className="field-help">Manual secret: <code>{enrollment.secret}</code></p><label>6-digit code<input value={code} onChange={(e)=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" /></label>{error&&<div className="alert alert-error">{error}</div>}<button className="button button-primary" type="button" onClick={verify}>Verify and enable MFA</button></section>
  if(verifiedFactorId)return <section className="card form-stack"><h2>Complete two-factor authentication</h2><p className="muted">Your account already has a verified authenticator. Enter its current code to elevate this session to AAL2.</p><label>6-digit code<input value={code} onChange={(e)=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" /></label>{error&&<div className="alert alert-error">{error}</div>}<button className="button button-primary" type="button" onClick={verify}>Verify code</button></section>
  return <section className="card status-card"><span className="status-dot">MFA not enrolled</span><h2>Protect your account with an authenticator app</h2><p>{adminRequired?'MFA is mandatory before administrative routes can be opened.':'MFA adds a second authentication factor to your account.'}</p>{error&&<div className="alert alert-error">{error}</div>}<button className="button button-primary" type="button" onClick={enroll}>Set up authenticator</button></section>
}
